name: Dependency Submissionon:

  push:

    branches: [ "main" ]

jobs:

  dependency-submission:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4

        with:

          distribution: 'temurin'java-version: '17'      - uses: gradle/actions/setup-gradle@v3

        with:

          dependency-graph: generate-and-submit
